Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -12,7 +12,7 @@ on:
           - pytest-host
           - docker-build
           - pytest-container
-          - deploy-test-webapp
+          - deploy-web_app
   # push:
   #   branches:
   #     - main
@@ -101,13 +101,17 @@ jobs:
       - name: Run tests in Docker container
         run: docker run --rm --mount type=bind,src=${{ github.workspace }},dst=/app ${{ secrets.DOCKER_USERNAME }}/flask-app:v1 python -m pytest tests/ -v
 
-  deploy-test-webapp:
-    if: ${{ inputs.job_to_run == 'deploy-test-webapp' }}
-    runs-on: ubuntu-24.04
+  deploy-web_app:
+    if: ${{ inputs.job_to_run == 'deploy-web_app' }}
     # needs: pytest-container
+    outputs:
+      app_url: $(terraform output -raw app_url)
     defaults:
-      run:
-        working-directory: ./terraform
+      runs-on: ubuntu-24.04
+      working-directory: ./terraform
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -117,11 +121,6 @@ jobs:
         run: |
           chmod +x zip-Dockerrun.aws.json.sh
           ./zip-Dockerrun.aws.json.sh
-      
-      - name: Set AWS credentials
-        run: |
-          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
-          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV      
       
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v3
@@ -134,42 +133,49 @@ jobs:
       - name: Terraform apply
         run: |
           terraform apply -auto-approve
-          echo "APP_URL=$(terraform output -raw app_url)" >> $GITHUB_ENV
       
-      - name: Test homepage
-        run: |
-          HTTP_CODE=$(curl -so /dev/null -w "%{http_code}" "${APP_URL}")
-          if [ "$HTTP_CODE" -ne 200 ]; then
-            printf "Error: Homepage test failed: Homepage returned $HTTP_CODE\n"
-            exit 1
-          fi
-            printf "Homepage test passed: Homepage returned $HTTP_CODE\n"
-      
-      - name: Test endpoints
-        run: |
-          test_endpoint() {
-            local url="$1"
-            local keyword="$2"
-            echo "Testing $url"
-            response=$(curl -s "$url")
-            if ! echo "$response" | grep -q "$keyword"; then
-              echo "Error: Missing '$keyword' in response: $response"
+    test-web_app_endpoints:
+      needs: deploy-web_app
+      defaults:
+        runs-on: ubuntu-24.04
+        env:
+          APP_URL: ${{ needs.deploy-web_app.outputs.app_url }}
+      working-directory: ./terraform
+      steps:
+        - name: Test homepage
+          run: |
+            HTTP_CODE=$(curl -so /dev/null -w "%{http_code}" "${APP_URL}")
+            if [ "$HTTP_CODE" -ne 200 ]; then
+              printf "Error: Homepage test failed: Homepage returned $HTTP_CODE\n"
               exit 1
             fi
-            echo "✅ $url passed"
-          }
-      
-          test_endpoint "${APP_URL}/api/v1.0/weather?location=London" '"weather"'
-          test_endpoint "${APP_URL}/api/v1.0/temperature?location=Manchester" '"temperature"'
-          test_endpoint "${APP_URL}/api/v1.0/wind?location=Glasgow" '"wind speed"'
-          test_endpoint "${APP_URL}/api/v1.0/humidity?location=Birmingham" '"humidity"'
+              printf "Homepage test passed: Homepage returned $HTTP_CODE\n"
+        
+        - name: Test endpoints
+          run: |
+            test_endpoint() {
+              local url="$1"
+              local keyword="$2"
+              echo "Testing $url"
+              response=$(curl -s "$url")
+              if ! echo "$response" | grep -q "$keyword"; then
+                echo "Error: Missing '$keyword' in response: $response"
+                exit 1
+              fi
+              echo "✅ $url passed"
+            }
+        
+            test_endpoint "${APP_URL}/api/v1.0/weather?location=London" '"weather"'
+            test_endpoint "${APP_URL}/api/v1.0/temperature?location=Manchester" '"temperature"'
+            test_endpoint "${APP_URL}/api/v1.0/wind?location=Glasgow" '"wind speed"'
+            test_endpoint "${APP_URL}/api/v1.0/humidity?location=Birmingham" '"humidity"'
 
-      - name: Clean up resources
-        if: always()
-        run: |
-          terraform destroy -auto-approve
-          echo "Resources cleaned up successfully."
-          aws s3 rm "s3://$(aws s3 ls | awk '{print $3}')" --recursive # Delete S3 bucket objects
-          aws s3api delete-bucket-policy --bucket "$(aws s3 ls | awk '{print $3}')" # Delete S3 bucket policy
-          aws s3api delete-bucket --bucket "$(aws s3 ls | awk '{print $3}')" # Delete S3 bucket
-          echo "S3 bucket and its contents deleted successfully."
+        - name: Clean up resources
+          if: always()
+          run: |
+            terraform destroy -auto-approve
+            echo "Resources cleaned up successfully."
+            aws s3 rm "s3://$(aws s3 ls | awk '{print $3}')" --recursive # Delete S3 bucket objects
+            aws s3api delete-bucket-policy --bucket "$(aws s3 ls | awk '{print $3}')" # Delete S3 bucket policy
+            aws s3api delete-bucket --bucket "$(aws s3 ls | awk '{print $3}')" # Delete S3 bucket
+            echo "S3 bucket and its contents deleted successfully."
